export const initialBoardState = [
    [
        { piece: "R", color: "black" },
        { piece: "N", color: "black" },
        { piece: "B", color: "black" },
        { piece: "Q", color: "black" },
        { piece: "K", color: "black" },
        { piece: "B", color: "black" },
        { piece: "N", color: "black" },
        { piece: "R", color: "black" },
    ],
    [
        { piece: "", color: "black" },
        { piece: "", color: "black" },
        { piece: "", color: "black" },
        { piece: "", color: "black" },
        { piece: "", color: "black" },
        { piece: "", color: "black" },
        { piece: "", color: "black" },
        { piece: "", color: "black" },
    ],
    [
        { piece: null, color: null },
        { piece: null, color: null },
        { piece: null, color: null },
        { piece: null, color: null },
        { piece: null, color: null },
        { piece: null, color: null },
        { piece: null, color: null },
        { piece: null, color: null },
    ],
    [
        { piece: null, color: null },
        { piece: null, color: null },
        { piece: null, color: null },
        { piece: null, color: null },
        { piece: "R", color: "white" },
        { piece: null, color: null },
        { piece: null, color: null },
        { piece: null, color: null },
    ],
    [
        { piece: null, color: null },
        { piece: null, color: null },
        { piece: null, color: null },
        { piece: null, color: null },
        { piece: null, color: null },
        { piece: null, color: null },
        { piece: "R", color: "white" },
        { piece: null, color: null },
    ],
    [
        { piece: null, color: null },
        { piece: null, color: null },
        { piece: "R", color: "white" },
        { piece: null, color: null },
        { piece: null, color: null },
        { piece: null, color: null },
        { piece: null, color: null },
        { piece: null, color: null },
    ],
    [
        { piece: "", color: "white" },
        { piece: "", color: "white" },
        { piece: "", color: "white" },
        { piece: "", color: "white" },
        { piece: "", color: "white" },
        { piece: "", color: "white" },
        { piece: "", color: "white" },
        { piece: "", color: "white" },
    ],
    [
        { piece: "R", color: "white" },
        { piece: "N", color: "white" },
        { piece: "B", color: "white" },
        { piece: "Q", color: "white" },
        { piece: "K", color: "white" },
        { piece: "B", color: "white" },
        { piece: "N", color: "white" },
        { piece: "R", color: "white" },
    ],
];
